### PR TITLE
DdiMedia_GetImage: fix vp context leak for error return

### PR DESCRIPTION
**Pull request by xuguangxin**
reproduce steps:
1. run gst-launch-1.0 -v tee name = t filesrc location = ~/cin.264 ! h264parse ! vaapih264dec ! t.  t. ! queue max-size-buffers=5 ! vaapipostproc ! "video/x-raw(memory:VASurface), format=NV12, width=320, height=240" ! vaapih264enc  ! fakesink
2. you will see "[LIBVA]:CRITICAL - DdiMedia_HeapDestroy:1382: APP does not destroy all the VPs"

gstvaapi will use vaGetImage to test driver capablities, it may give driver wrong input/output format
we need make sure no resource leak at anytime.

### CODE REVIEW

**Comment by xuguangxin** [comment]
@Xiaogangli-intel , any comment on this?

**Comment by xuguangxin** [comment]
@XinfengZhang @Xiaogang-Li are we ready to merge this?
thanks

**Comment by XinfengZhang** [comment]
LGTM , will merge it after test. thanks

**Comment by FurongZhang** [comment]
Looks good to me.

**Comment by xuguangxin** [comment]
thanks carl and furong

**Pull request merged**
