### PR TITLE
Enable QVBR for AVC DP encoding

### PR DESCRIPTION
**Pull request by ChenXiaomin36**
Change-Id: I1a22aa036bf9438c491e8749087c8aa12217dbb0
Signed-off-by: xiaominc <xiaomin.chen@intel.com>

### CODE REVIEW

**Comment by ChenXiaomin36** [comment]
Here are the answers:
1. Now after this patch, only AVC encoder will support QVBR.
2. Once this patch for AVC DP is merged, I will submit another PR for AVC lowpower encoder.
Thanks! @dvrogozh

**Comment by dvrogozh** [comment]
@ChenXiaomin36 : I see some strange behaviour on enabled qvbr. Could you, please, check on your side? Consider the following mediasdk command lines with _different_ bitrate settings (compare: -b 2500 and -b 4000, -MaxKbps 3000 and MaxKbps 4800):
```
./share/mfx/samples/sample_encode h264 -i 720p.yuv -o 30_se.h264 -w 1280 -h 720 -f 30 -b 2500 -u 1 -hw -vaapi -n 600 -r 1 -g 30 -MaxKbps 3000 -qvbr 30

./share/mfx/samples/sample_encode h264 -i 720p.yuv -o 48_se.h264 -w 1280 -h 720 -f 30 -b 4000 -u 1 -hw -vaapi -n 600 -r 1 -g 30 -MaxKbps 4800 -qvbr 30
```

The strange thing is that if you will check the quality of output streams, you will see that PSNR values are identical. Are there any limit in the driver which forces bitrates to be equal to this limit if user-specified bitrate is lower than this limit? I am looking into such a limit in mediasdk, but it seems this can be something on the driver side, because settings which mediasdk pass to VAEncMiscParameterRateControl look correct (my custom debug prints below added here: https://github.com/Intel-Media-SDK/MediaSDK/blob/master/_studio/mfx_lib/shared/src/mfx_h264_encode_vaapi.cpp#L210):
```
>>> rate_param->bits_per_second=2999296, rate_param->window_size=300000, rate_param->target_percentage=83, rate_param->quality_factor=30

>>> rate_param->bits_per_second=4799488, rate_param->window_size=480000, rate_param->target_percentage=83, rate_param->quality_factor=30
```

Note: you need this PR Intel-Media-SDK/MediaSDK#656 to try QVBR under mediasdk.

**Comment by dvrogozh** [comment]
@ChenXiaomin36 : any feedback on the noted behavior?

**Comment by ChenXiaomin36** [comment]
@dvrogozh : I have tried the command lines you mentioned, compared different bitrate settings. I also got the result that PSNR values were the same for these two output bitstreams. I need to look into the driver codes,  perhaps even lower level realization for QVBR. I will give out the feedback once I have some findings. Thanks!

**Comment by dvrogozh** [comment]
@ChenXiaomin36 : I have submitted #379 to track issue with the same quality for the different QVBR settings.

**Pull request merged**
