### PR TITLE
[VP]Fix issue #272.

### PR DESCRIPTION
**Pull request by Jister**
Add output region of target surface

### CODE REVIEW

**Comment by xuguangxin** [comment]
@Jister , great. this fixed my issue. 

thanks

**Comment by xuguangxin** [comment]
@Jister , one thing I want double confirm. if we really follow alpha blending define. Why we need specail handle alpha value 0? Is this mean the alpha value does not work ?

**Comment by Jister** [comment]
@xuguangxin Actually this issue is not an alpha blending case, multi-input surfaces are written to different region of the same output surface after scaling, if color fill is executed, the surface data outside of the region will sure be overwritten by the data of background color, so here the fix handle alpha value 0 is to judge whether color fill need to be executed. For alpha blending usage, you need to call blending API to do it.

**Comment by Jister** [comment]
@xuguangxin By the way, for color fill cases, currently our driver will always ignore alpha channel and fill the alpha with 0xFF, this is another story, and I have fixed it and will check in soon.

**Comment by xuguangxin** [comment]
No, the definition for the background is not color fill, it's alpha blending. https://github.com/intel/libva/blob/master/va/va_vpp.h#L871.
alpha value 0 and 0xff is just a special case for the alpha blending.

thanks

**Comment by Jister** [comment]
As libva says "Background color used to **fill in pixels** that reside outside of the specified \ref output_region.", that means colorfill and colorfill will always use this value. For alpha blending case, when primary layer need to do color fill (i.e. primary layer don't represent the whole surface), we will also use this value as background color and blend the primary and background together, but when it's 0, the background will be transparent, so we don't need to fill it. 
For sublayer, we'll use the alpha value in VABlendState to do blending. You can refer to:
https://github.com/intel/libva/blob/30c751f7b74c43021f33361c1baf2aa92acd0317/va/va_vpp.h#L482

Thanks

**Comment by xuguangxin** [comment]
@Jister 
In this case, the alpha value has no much mean.
It only can be 0x0 or 0xff.
@xhaihao  and @XinfengZhang, could you explain more about the API.
If we can only accept 0x0 and 0xff for the alpha. we'd better document it down in headers.

thanks

**Comment by Jister** [comment]
The change affect blending cases, will backout and create another fix.

**Comment by xuguangxin** [comment]
Please consider use Alpha blending for this API. else we need ask @xhaihao and @XinfengZhang change the libva API description.

**Comment by Jister** [comment]
Created another pull request #324

**Pull request merged**
