### PR TITLE
Implement continuous ring buffer logic for render target table

### PR DESCRIPTION
**Pull request by vshampor**

### CODE REVIEW

**Comment by vshampor** [comment]
@XinfengZhang, please take a look at this.

**Comment by vshampor** [comment]
Greetings, @XinfengZhang!

What is the status on this PR and ETA to merge?

**Comment by XinfengZhang** [comment]
LGTM

**Comment by XinfengZhang** [comment]
will merge, after some tests

**Comment by vshampor** [comment]
Greetings, @XinfengZhang!

Surely the tests have finished running by now?

**Pull request merged**
