### PR TITLE
remove the deprecated items of va from driver

### PR DESCRIPTION
**Pull request by XinfengZhang**
Signed-off-by: XinfengZhang <carl.zhang@intel.com>

### CODE REVIEW

**Comment by uartie** [comment]
There are also some va deprecations used in media_ddi_encode_hevc.cpp (VAEncPackedHeaderHEVC_SEI)

**Comment by XinfengZhang** [comment]
@uartie  thanks , will remove it. all packed header should use VAEncPackedHeaderRawData except SPS PPS SLCHeader

**Comment by XinfengZhang** [comment]
fix #88

**Comment by uartie** [comment]
LGTM

**Comment by uartie** [comment]
Can you merge this patch?  Without this patch, the driver will not compile on newer distros (w/GCC 6.x+) since all warnings are being treated as errors (since commit fa0d40ee6d3d7ec34478da166b2740eaf9b7c0ce).

**Comment by XinfengZhang** [comment]
@uartie will merge it ASAP
@dvrogozh  hi Dmitry, will MSDK remove these deprecated item also?

**Comment by dvrogozh** [comment]
I am not familiar with this topic. You need to ask @onabiull.

**Comment by dmitryermilov** [comment]
@XinfengZhang, you must have meant me:) 
MediaSDK changes have been prepared: https://github.com/Intel-Media-SDK/MediaSDK/pull/68

**Comment by onabiull** [comment]
MSDK changes merged

**Pull request merged**
