### PR TITLE
set vp8 encode max resolution to 4k

### LINKED ISSUE #565: The maximum resolution for VP8 Encoding is (1920, 1920)
When I query the maximum resolution by vaQuerySurfaceAttributes with VAProfileVP8Version0_3 and VAEntrypointEncSlice, the values of VASurfaceAttribMaxWidth and VASurfaceAttribMaxHeight both are 1920.
https://github.com/intel/media-driver/blob/6c99fc02c0fd6adaf7f00b1cf571769ebf62e5a5/media_driver/linux/common/ddi/media_libva_caps.cpp#L2593
https://github.com/intel/media-driver/blob/4c0407c16ebcf08ea5adfcce2efdcab6dfa7a35f/media_driver/agnostic/common/codec/shared/codec_def_common_encode.h#L53

With intel-vaapi-driver, they both are 4096.

This seems a regression from user perspective.
Could you tell me the plan about increasing the maximum resolution for VP8 HW Encoding?

Thanks in advance.

### PR DESCRIPTION
**Pull request by XinfengZhang**
fixes #565

Signed-off-by: XinfengZhang <carl.zhang@intel.com>

### CODE REVIEW

**Comment by azhar904** [comment]
@XinfengZhang Can you please update this patch.

**Comment by XinfengZhang** [comment]
@azhar904 updated , please help check.

**Comment by rosetta-jpn** [comment]
Hi, may I ask you to check in this change?

Thanks!

**Comment by azhar904** [comment]
@XinfengZhang I have verified this change.

**Pull request merged**
