### PR TITLE
[Encode] Add QVBR rate control mode for AV1

### PR DESCRIPTION
**Pull request by BlakeB415**
Relies on https://github.com/oneapi-src/oneVPL-intel-gpu/pull/312

### CODE REVIEW

**Comment by leyu-yao** [comment]
Hi @BlakeB415.
Encoding in BRC mode requires firmware to work together with engines. Our huc firmware does not support QVBR. As a result, this patch will not get the expected quality.
May I know in which scenario you would like to use QVBR? And is current VBR and ICQ not meeting your requirement?

**Comment by BlakeB415** [comment]
> Hi @BlakeB415. Encoding in BRC mode requires firmware to work together with engines. Our huc firmware does not support QVBR. As a result, this patch will not get the expected quality. May I know in which scenario you would like to use QVBR? And is current VBR and ICQ not meeting your requirement?

The specific behavior we want is more like capped ICQ (similar to capped CRF) to where the ICQ BRC doesn’t exceed the set max bitrate. QVBR might not be the correct RC mode for this though considering this.

We want to ensure the bitrate stays within a certain range while also having it use the ICQ target quality.

**Comment by leyu-yao** [comment]
> > Hi @BlakeB415. Encoding in BRC mode requires firmware to work together with engines. Our huc firmware does not support QVBR. As a result, this patch will not get the expected quality. May I know in which scenario you would like to use QVBR? And is current VBR and ICQ not meeting your requirement?
> 
> The specific behavior we want is more like capped ICQ (similar to capped CRF) where the ICQ BRC does not exceed the set max bitrate. QVBR might not be the correct RC mode for this use case though.
> 
> We want to ensure the bitrate stays within a certain range while also having it use the ICQ target quality scale.
> 
> This patch does have the result I needed, from my testing at least.

Did you try if you can get expected quality if using VBR mode? 
As our firmware does not support QVBR currently. So due to our code check-in policy, we cannot merge this PR to our mainline. If this PR can meet your requirement, I'd prefer to keep it as part of private build.

**Comment by BlakeB415** [comment]
> > > Hi @BlakeB415. Encoding in BRC mode requires firmware to work together with engines. Our huc firmware does not support QVBR. As a result, this patch will not get the expected quality. May I know in which scenario you would like to use QVBR? And is current VBR and ICQ not meeting your requirement?
> > 
> > 
> > The specific behavior we want is more like capped ICQ (similar to capped CRF) where the ICQ BRC does not exceed the set max bitrate. QVBR might not be the correct RC mode for this use case though.
> > We want to ensure the bitrate stays within a certain range while also having it use the ICQ target quality scale.
> > This patch does have the result I needed, from my testing at least.
> 
> Did you try if you can get expected quality if using VBR mode? As our firmware does not support QVBR currently. So due to our code check-in policy, we cannot merge this PR to our mainline. If this PR can meet your requirement, I'd prefer to keep it as part of private build.

We tried VBR but the output files are larger than what we can achieve with ICQ given the perceived quality.

I'll close this and the linked issue. Thank you.

**Pull request closed without merging**
