### PR TITLE
Map VA_FOURCC_A2R10G10B10 to Media_Format_B10G10R10A2

### PR DESCRIPTION
**Pull request by xhaihao**

### CODE REVIEW

**Comment by xhaihao** [comment]
@XinfengZhang @FurongZhang  was medi-dirver not configured to use libva master for the travis CI build? VA_FOURCC_A2R10G10B10 was added into libva

**Comment by XinfengZhang** [comment]
@Sherry-Lin , could you help to check whether the travis build is using the latest commit?

**Comment by Sherry-Lin** [comment]
There is deploy key issue in hub.docker, see https://github.com/docker/hub-feedback/issues/416#issuecomment-478682342. I added Libva in travis build too so that we don't need to refresh the docker image. Please rebase to latest commit and try again. Thanks.

**Comment by xhaihao** [comment]
I still see this issue:

opt/src/media-driver/media_driver/linux/common/ddi/media_libva.cpp: In function 'DDI_MEDIA_FORMAT DdiMedia_OsFormatToMediaFormat(int32_t, int32_t)':
/opt/src/media-driver/media_driver/linux/common/ddi/media_libva.cpp:478:14: error: 'VA_FOURCC_A2R10G10B10' was not declared in this scope
         case VA_FOURCC_A2R10G10B10:
              ^~~~~~~~~~~~~~~~~~~~~
media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/build.make:8366: recipe for target 'media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/linux/common/ddi/media_libva.cpp.o' failed
make[2]: *** [media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/linux/common/ddi/media_libva.cpp.o] Error 1

**Comment by xhaihao** [comment]
@XinfengZhang @FurongZhang any comment/concern on this PR?

**Pull request merged**
