### PR TITLE
Add MEDIA_BUILD_HARDENING option

### PR DESCRIPTION
**Pull request by ffontaine**
Add MEDIA_BUILD_HARDENING option to allow the user to disable hardening options such as stack-protector-all or FORTIFY SOURCE 2 which are not always available (e.g. fortify source 2 is only available on glibc >= 6 and not musl/uclibc-ng)

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>

### CODE REVIEW

**Review by Sherry-Lin — APPROVED** [review]
@haizhouxu could you take a look?

**Comment by bkuhls** [comment]
ping

**Comment by Sherry-Lin** [comment]
@cqian2  could you take a look?

**Review by haizhouxu — APPROVED** [review]

**Comment by ffontaine** [comment]
Do you plan to merge this PR or do you have additional comments?

**Comment by dvrogozh** [comment]
@ffontaine: merged.

**Comment by ffontaine** [comment]
Indeed, thanks

**Pull request merged**
