### PR TITLE
Add CI builds that disable MTL and ARL support

### PR DESCRIPTION
**Pull request by mattst88**
Cc: @XinfengZhang, @Sherry-Lin

I expect the MTL-disabled build to fail with:

```
  In file included from /root/projects/intel/media-driver/media_softlet/media_interface/media_interfaces_arl/media_interfaces_arl.cpp:30:    
  /root/projects/intel/media-driver/media_softlet/media_interface/media_interfaces_arl/media_interfaces_arl.h:32:10: fatal error: 'media_interfaces_mtl.h' file not found    
  #include "media_interfaces_mtl.h"    
          ¦^~~~~~~~~~~~~~~~~~~~~~~~    
  1 error generated.    
```

### CODE REVIEW

**Comment by Sherry-Lin** [comment]
@MicroYY will check it.

**Comment by MicroYY** [comment]
Hi @mattst88 ARL is derivative platform of MTL, so they share almost the same code implementation. You may need to add cmake option dependency to turn off ARL if MTL is off, or combine them with 1 option, just like the gen12.

**Comment by mattst88** [comment]
Thanks! I'll update the PR tomorrow.

**Comment by mattst88** [comment]
Fixed.

**Review by MicroYY — APPROVED** [review]

**Comment by mattst88** [comment]
ping

**Pull request merged**
