### PR TITLE
Add VPP YUV 12bit support

### PR DESCRIPTION
**Pull request by Effiey**
Enable VPP YUV 12bit(P010,Y212,Y412) in media driver

### CODE REVIEW

**Review by FurongZhang — APPROVED** [review]
Looks good to me.

**Comment by nyanmisaka** [comment]
Hi! @XinfengZhang Any updates on this?

We need to convert Y412 to P010 and it is already supported on Windows.

**Comment by FurongZhang** [comment]
We have already supported this. This PR has been merged into the open source code.

**Comment by Effiey** [comment]
> We have already supported this. This PR has been merged into the open source code.

Done.
Thanks for the reminder.

**Pull request closed without merging**
