### PR TITLE
fix github issue#313

### PR DESCRIPTION
**Pull request by yangnin**
1. don't override linker flag from user

Signed-off-by: Yang, Ning <ning.yang@intel.com>

### CODE REVIEW

**Comment by Sherry-Lin** [comment]
#313

**Comment by chivakker** [comment]
This patch by itself works fine when compiling media-driver standalone, meaning gmmlib is found by pkg-config tool but gmmlib sources are not available in the same workspace. 

Unfortunately, the default behavior for media-driver is to look for gmmlib in the same folder (workspace) if it finds gmmlib, then it will get compiled.  gmmlib fails to compile with this change. 

media-driver could remove searching for gmmlib sources in the same folder.

**Comment by dvrogozh** [comment]
> Unfortunately, the default behavior for media-driver is to look for gmmlib in the same folder (workspace) if it finds gmmlib, then it will get compiled. gmmlib fails to compile with this change.

I did not see such behavior. For me if gmmlib is found in pkg-config it ignores gmmlib sources. But if it failed to find them it then it indeed will attempt to build from sources. Questions:
1. What is your cmake configuration line?
2. Are you sure that gmmlib was found via pkg-config? Check this manually, please.

**Comment by chivakker** [comment]
> > Unfortunately, the default behavior for media-driver is to look for gmmlib in the same folder (workspace) if it finds gmmlib, then it will get compiled. gmmlib fails to compile with this change.
> 
> I did not see such behavior. For me if gmmlib is found in pkg-config it ignores gmmlib sources. But if it failed to find them it then it indeed will attempt to build from sources. Questions:
>
I have to correct myself, your description is what actually happens.  In any case when pkg-config doesn't find anything and gmmlib is compiled within the driver it fails with this patch alone.  A proper fix on gmmlib would be necessary. 
 
> 1. What is your cmake configuration line?
PKG_CONFIG_PATH=<prefix>/lib/pkgconfig:<prefix>/lib64/pkgconfig:$PKG_CONFIG_PATH cmake ../media-driver -DCMAKE_INSTALL_PREFIX=<prefix> -DMEDIA_VERSION="2.0.0"

> 2. Are you sure that gmmlib was found via pkg-config? Check this manually, please.
So, when gmmlib is found, compilation breaks with the above config and it cannot find:

<prefix>/include/igdgmm/inc/External/Common/GmmCommonExt.h:60:10: fatal error: ../../../Utility/CpuSwizzleBlt/CpuSwizzleBlt.c: No such file or directory

 /usr/lib64/ccache/c++  -DHEVC_FEI_ENABLE_CMRT -DIGFX_GEN10_CNL_SUPPORTED -DIGFX_GEN10_SUPPORTED -DIGFX_GEN11_ICLLP_SUPPORTED -DIGFX_GEN11_SUPPORTED -DIGFX_GEN8_BDW_SUPPORTED -DIGFX_GEN8_SUPPORTED -DIGFX_GEN9_BXT_SUPPORTED -DIGFX_GEN9_CFL_SUPPORTED -DIGFX_GEN9_GLK_SUPPORTED -DIGFX_GEN9_KBL_SUPPORTED -DIGFX_GEN9_SKL_SUPPORTED -DIGFX_GEN9_SUPPORTED -DUFO_VERSION=\"2.0.0\" -DVEBOX_AUTO_DENOISE_SUPPORTED=1 -D_AVC_DECODE_SUPPORTED -D_AVC_ENCODE_VDENC_SUPPORTED -D_AVC_ENCODE_VME_SUPPORTED -D_COMMON_ENCODE_SUPPORTED -D_DECODE_PROCESSING_SUPPORTED -D_HEVC_DECODE_SUPPORTED -D_HEVC_ENCODE_VDENC_SUPPORTED -D_HEVC_ENCODE_VME_SUPPORTED -D_JPEG_DECODE_SUPPORTED -D_JPEG_ENCODE_SUPPORTED -D_MMC_SUPPORTED -D_MPEG2_DECODE_SUPPORTED -D_MPEG2_ENCODE_VME_SUPPORTED -D_RELEASE -D_VC1_DECODE_SUPPORTED -D_VP8_DECODE_SUPPORTED -D_VP8_ENCODE_SUPPORTED -D_VP9_DECODE_SUPPORTED -D_VP9_ENCODE_VDENC_SUPPORTED -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -D__VPHAL_SFC_SUPPORTED=1 -I<prefix>/include -I<prefix>gcmedia-driver/media_driver/linux/common/os/libdrm/include -I<prefix>/include/igdgmm/util -I<prefix>/include/igdgmm/inc/common -I<prefix>/include/igdgmm/inc -I<prefix>/include/igdgmm/GmmLib/inc -I<prefix>/include/igdgmm/GmmLib -I<prefix>/include/igdgmm -I<prefix><workspace>/media-driver/media_driver/agnostic/common/cm -I<prefix><workspace>/media-driver/media_driver/agnostic/common/codec/hal -I<prefix><workspace>/media-driver/media_driver/agnostic/common/codec/kernel -I<prefix><workspace>/media-driver/media_driver/agnostic/common/codec/shared -I<prefix><workspace>/media-driver/media_driver/agnostic/common/heap_manager -I<prefix><workspace>/media-driver/media_driver/agnostic/common/hw/vdbox -I<prefix><workspace>/media-driver/media_driver/agnostic/common/hw -I<prefix><workspace>/media-driver/media_driver/agnostic/common/media_interfaces -I<prefix><workspace>/media-driver/media_driver/agnostic/common/os -I<prefix><workspace>/media-driver/media_driver/agnostic/common/renderhal -I<prefix><workspace>/media-driver/media_driver/agnostic/common/shared -I<prefix><workspace>/media-driver/media_driver/agnostic/common/vp/hal -I<prefix><workspace>/media-driver/media_driver/agnostic/common/vp/kdll -I<prefix><workspace>/media-driver/media_driver/agnostic/common/vp/kernel -I<prefix><workspace>/media-driver/media_driver/agnostic/gen8/cm -I<prefix><workspace>/media-driver/media_driver/agnostic/gen8/codec/hal -I<prefix><workspace>/media-driver/media_driver/agnostic/gen8/codec/kernel -I<prefix><workspace>/media-driver/media_driver/agnostic/gen8/hw/vdbox -I<prefix><workspace>/media-driver/media_driver/agnostic/gen8/hw -I<prefix><workspace>/media-driver/media_driver/agnostic/gen8/renderhal -I<prefix><workspace>/media-driver/media_driver/agnostic/gen8/vp/hal -I<prefix><workspace>/media-driver/media_driver/agnostic/gen8/vp/kernel -I<prefix><workspace>/media-driver/media_driver/agnostic/gen8_bdw/codec/hal -I<prefix><workspace>/media-driver/media_driver/agnostic/gen8_bdw/hw/vdbox -I<prefix><workspace>/media-driver/media_driver/agnostic/gen8_bdw/media_interfaces -I<prefix><workspace>/media-driver/media_driver/agnostic/gen8_bdw/renderhal -I<prefix><workspace>/media-driver/media_driver/agnostic/gen9/cm -I<prefix><workspace>/media-driver/media_driver/agnostic/gen9/codec/hal -I<prefix><workspace>/media-driver/media_driver/agnostic/gen9/codec/kernel -I<prefix><workspace>/media-driver/media_driver/agnostic/gen9/hw/vdbox -I<prefix><workspace>/media-driver/media_driver/agnostic/gen9/hw -I<prefix><workspace>/media-driver/media_driver/agnostic/gen9/renderhal -I<prefix><workspace>/media-driver/media_driver/agnostic/gen9/vp/hal -I<prefix><workspace>/media-driver/media_driver/agnostic/gen9/vp/kernel -I<prefix><workspace>/media-driver/media_driver/agnostic/gen9_bxt/codec/hal -I<prefix><workspace>/media-driver/media_driver/agnostic/gen9_bxt/codec/kernel -I<prefix><workspace>/media-driver/media_driver/agnostic/gen9_bxt/hw/vdbox -I<prefix><workspace>/media-driver/media_driver/agnostic/gen9_bxt/media_interfaces -I<prefix><workspace>/media-driver/media_driver/agnostic/gen9_bxt/vp/hal -I<prefix><workspace>/media-driver/media_driver/agnostic/gen9_skl/codec/hal -I<prefix><workspace>/media-driver/media_driver/agnostic/gen9_skl/codec/cmrt_kernel -I<prefix><workspace>/media-driver/media_driver/agnostic/gen9_skl/hw/vdbox -I<prefix><workspace>/media-driver/media_driver/agnostic/gen9_skl/media_interfaces -I<prefix><workspace>/media-driver/media_driver/agnostic/gen9_cfl/media_interfaces -I<prefix><workspace>/media-driver/media_driver/agnostic/gen9_glk/codec/hal -I<prefix><workspace>/media-driver/media_driver/agnostic/gen9_glk/hw/vdbox -I<prefix><workspace>/media-driver/media_driver/agnostic/gen9_glk/media_interfaces -I<prefix><workspace>/media-driver/media_driver/agnostic/gen9_glk/vp/hal -I<prefix><workspace>/media-driver/media_driver/agnostic/gen9_kbl/codec/hal -I<prefix><workspace>/media-driver/media_driver/agnostic/gen9_kbl/codec/kernel -I<prefix><workspace>/media-driver/media_driver/agnostic/gen9_kbl/hw/vdbox -I<prefix><workspace>/media-driver/media_driver/agnostic/gen9_kbl/media_interfaces -I<prefix><workspace>/media-driver/media_driver/agnostic/gen10/cm -I<prefix><workspace>/media-driver/media_driver/agnostic/gen10/codec/hal -I<prefix><workspace>/media-driver/media_driver/agnostic/gen10/codec/kernel -I<prefix><workspace>/media-driver/media_driver/agnostic/gen10/codec/share -I<prefix><workspace>/media-driver/media_driver/agnostic/gen10/hw/vdbox -I<prefix><workspace>/media-driver/media_driver/agnostic/gen10/hw -I<prefix><workspace>/media-driver/media_driver/agnostic/gen10/renderhal -I<prefix><workspace>/media-driver/media_driver/agnostic/gen10/vp/hal -I<prefix><workspace>/media-driver/media_driver/agnostic/gen10/vp/kernel -I<prefix><workspace>/media-driver/media_driver/agnostic/gen10_cnl/media_interfaces -I<prefix><workspace>/media-driver/media_driver/agnostic/gen11/cm -I<prefix><workspace>/media-driver/media_driver/agnostic/gen11/codec/hal -I<prefix><workspace>/media-driver/media_driver/agnostic/gen11/codec/kernel -I<prefix><workspace>/media-driver/media_driver/agnostic/gen11/codec/share -I<prefix><workspace>/media-driver/media_driver/agnostic/gen11/hw/vdbox -I<prefix><workspace>/media-driver/media_driver/agnostic/gen11/hw -I<prefix><workspace>/media-driver/media_driver/agnostic/gen11/renderhal -I<prefix><workspace>/media-driver/media_driver/agnostic/gen11/vp/hal -I<prefix><workspace>/media-driver/media_driver/agnostic/gen11_icllp/codec/hal -I<prefix><workspace>/media-driver/media_driver/agnostic/gen11_icllp/codec/kernel -I<prefix><workspace>/media-driver/media_driver/agnostic/gen11_icllp/media_interfaces -I<prefix><workspace>/media-driver/media_driver/agnostic/gen11_icllp/vp/hal -I<prefix><workspace>/media-driver/media_driver/agnostic/gen11_icllp/vp/kernel -I<prefix><workspace>/media-driver/media_driver/linux/common/cm -I<prefix><workspace>/media-driver/media_driver/linux/common/codec/ddi -I<prefix><workspace>/media-driver/media_driver/linux/common/cp/ddi -I<prefix><workspace>/media-driver/media_driver/linux/common/cp/hw -I<prefix><workspace>/media-driver/media_driver/linux/common/cp/os -I<prefix><workspace>/media-driver/media_driver/linux/common/cp/shared -I<prefix><workspace>/media-driver/media_driver/linux/common/ddi -I<prefix><workspace>/media-driver/media_driver/linux/common/os -I<prefix><workspace>/media-driver/media_driver/linux/common/vp/ddi -I<prefix><workspace>/media-driver/media_driver/linux/gen8/ddi -I<prefix><workspace>/media-driver/media_driver/linux/gen9/ddi -I<prefix><workspace>/media-driver/media_driver/linux/gen9_bxt/ddi -I<prefix><workspace>/media-driver/media_driver/linux/gen9_skl/ddi -I<prefix><workspace>/media-driver/media_driver/linux/gen9_kbl/ddi -I<prefix><workspace>/media-driver/media_driver/linux/gen9_glk/ddi -I<prefix><workspace>/media-driver/media_driver/linux/gen9_cfl/ddi -I<prefix><workspace>/media-driver/media_driver/linux/gen10/ddi -I<prefix><workspace>/media-driver/media_driver/linux/gen10_cnl/ddi -I<prefix><workspace>/media-driver/media_driver/linux/gen11/codec/ddi -I<prefix><workspace>/media-driver/media_driver/linux/gen11/ddi -I<prefix><workspace>/media-driver/../gmmlib/Source/inc -I<prefix><workspace>/media-driver/../gmmlib/Source/inc/common -I<prefix><workspace>/media-driver/../gmmlib/Source/inc/platform/iAlm -I<prefix><workspace>/media-driver/../gmmlib/Source/inc/umKmInc -I<prefix><workspace>/media-driver/../gmmlib/Source/GmmLib/inc -I<prefix><workspace>/media-driver/../huc/inc -I/linux  -Wno-reorder -Wsign-promo -Wnon-virtual-dtor -Wno-invalid-offsetof -fvisibility-inlines-hidden -fno-use-cxa-atexit -frtti -fexceptions -fpermissive -fcheck-new -std=c++1y -std=c++11 -O2 -DNDEBUG -fPIC   -Werror -Wall -Winit-self -Wpointer-arith -Wno-unused -Wno-unknown-pragmas -Wno-endif-labels -Wno-comments -Wno-sign-compare -Wno-attributes -Wno-narrowing -Wno-overflow -Wno-parentheses -Werror=implicit-function-declaration -Werror=address -Werror=format-security -Werror=non-virtual-dtor -Werror=return-type -march=corei7 -mpopcnt -msse -msse2 -msse3 -mssse3 -msse4.1 -msse4.2 -msse4 -mfpmath=sse -finline-functions -fno-short-enums -Wa,--noexecstack -fno-strict-aliasing -DUSE_MMX -DUSE_SSE -DUSE_SSE2 -DUSE_SSE3 -DUSE_SSSE3 -fmessage-length=0 -fstack-protector -fdata-sections -ffunction-sections -m64 -DLINUX=1 -DLINUX -DNO_RTTI -DNO_EXCEPTION_HANDLING -DINTEL_NOT_PUBLIC -g -fvisibility=hidden -funswitch-loops -Wl,--gc-sections -D_AMD64_ -D__CT__ -D__linux__ -fPIC -fno-tree-pre -Wl,--no-as-needed -O2 -D_FORTIFY_SOURCE=2 -fno-omit-frame-pointer -finline-limit=100 -o CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/common/cm/cm_device_rt.cpp.o -c <prefix><workspace>/media-driver/media_driver/agnostic/common/cm/cm_device_rt.cpp

**Comment by chivakker** [comment]
> @chivakker : sorry, from what you wrote I don't understand in which case you see the error? You see the error when gmmlib _can_ be found via pkg-config?

Yes when gmmlib is found via pkg-config and when using prefix and that prefix != /usr

**Comment by dvrogozh** [comment]
This scenario perfectly works for me...

**Comment by dvrogozh** [comment]
We talked with @chivakker : and we clearly see the difference between build behavior between CentOS 7.5 centric build (me) and Ubuntu centric (@chivakker). However, this build failure is definitely some other issue non related to the current PR. I suggest to file another bug for it.

**Comment by chivakker** [comment]
> We talked with @chivakker : and we clearly see the difference between build behavior between CentOS 7.5 centric build (me) and Ubuntu centric (@chivakker). However, this build failure is definitely some other issue non related to the current PR. I suggest to file another bug for it.

I agree, I believe most of that is captured on issue https://github.com/intel/media-driver/issues/315.  If a separate issue is necessary let me know.

**Comment by Sherry-Lin** [comment]
@dvrogozh Verifying. We will merge it today

**Pull request merged**
