### PR TITLE
Fix documentation formatting

### PR DESCRIPTION
**Pull request by Hi-Angel**

### CODE REVIEW

**Comment by Hi-Angel** [comment]
ping

**Comment by Sherry-Lin** [comment]
Could you rebase to latest code?

**Comment by Hi-Angel** [comment]
Sure, done. I had to change last commit because someone fixed the original formatting problem that commit was fixing; but at the same time they introduced new code snippets that weren't surrounded by `<code>`, so had to re-fix that 😄

**Review by Sherry-Lin — APPROVED** [review]
looks good

**Pull request merged**
