### PR TITLE
change the max_display_attributes to be zero

### PR DESCRIPTION
**Pull request by XinfengZhang**
set the max_display_attributes to be zero, middle ware should check the vaMaxNumDisplayAttributes, if it is zero, should not call the vaGet/QueryDisplayAttributes.

### CODE REVIEW

**Comment by XinfengZhang** [comment]
#17

**Comment by uartie** [comment]
LGTM

**Comment by XinfengZhang** [comment]
https://github.com/01org/libva/pull/165
dependancy

**Comment by uartie** [comment]
libva dependency is merged

**Comment by uartie** [comment]
can you merge this?

**Comment by XinfengZhang** [comment]
@uartie  will merge  the #96  first , then merge this PR. will merge it ASAP

**Pull request merged**
