### PR TITLE
Add Padding to Gen11

### PR DESCRIPTION
**Pull request by leyu-yao**

### CODE REVIEW

**Review by Bossonor — APPROVED** [review]
LGTM

**Comment by XinfengZhang** [comment]
solution should be unified as #1722

**Comment by leyu-yao** [comment]
> solution should be unified as #1722

Yes. That would be expected.

**Comment by leyu-yao** [comment]
Landed on https://github.com/intel/media-driver/commit/0a9bd3dca52935cbc4501227a9a6ade0c4fe8bd7
So closing this PR

**Pull request closed without merging**
