### PR TITLE
Fix mos build issue

### LINKED ISSUE #4: Compile error c++ (GCC) 7.2.1 20170915 (not a constant expression)
With `c++ (GCC) 7.2.1 20170915` (i.e. Fedora 27 default GCC version), the following compiler error is generated:
```
In file included from <snip>/media_driver/agnostic/common/os/mos_context.cpp:28:0:
<snip>/media_driver/linux/common/os/mos_context_specific.h:63:67: error: value ‘18446744073709551615’ of type ‘void*’ is not a constant expression
     constexpr static void* MOS_LINUX_SHM_INVALID       = (void *)-1;
                                                                   ^
```

### PR DESCRIPTION
**Pull request by LuoIvan**
fix #4

### CODE REVIEW

**Comment by mypopydev** [comment]
I think the 2 commits need to rebase to 1 commit

**Comment by LuoIvan** [comment]
Combine 2 commits into 1

**Comment by uartie** [comment]
Is there an ETA on when this will be merged?

**Comment by oliver-sang** [comment]
@uartie thanks for reminding. I will talk with @LuoIvan tomorrow then merge or supply an ETA

**Pull request merged**
