### PR TITLE
Fix HEVC encoding failed on P frame issue on GLK

### LINKED ISSUE #733: GPU hangs while encoding with Ubuntu repo driver
Hi,

currently I am on an Ubuntu Server 19.04 machine with the J4105 Gemini Lake CPU.
I followed these wiki guides to get the Media SDK working with ffmpeg:

https://github.com/Intel-Media-SDK/MediaSDK/wiki/Intel-media-stack-on-Ubuntu
https://github.com/Intel-Media-SDK/MediaSDK/wiki/Build-and-use-ffmpeg-with-MediaSDK

I got all libraries/drivers from the repository and built ffmpeg with the necessary configuration flags.

The decoding examples run well but encoding fails:

MFX sample_encode:

```
GPU hang happened
[ERROR], sts=MFX_ERR_GPU_HANG(-21), Run, m_pmfxENC->EncodeFrameAsync failed at /build/intel-mediasdk-AzMSof/intel-mediasdk-18.4.1/samples/sample_encode/src/pipeline_encode.cpp:2085
[ERROR], sts=MFX_ERR_GPU_HANG(-21), main, pPipeline->Run failed at /build/intel-mediasdk-AzMSof/intel-mediasdk-18.4.1/samples/sample_encode/src/sample_encode.cpp:1364
Frame number: 2
```

ffmpeg encoding/transcoding:

```
[hevc_qsv @ 0x55a354f29340] Unknown FrameType, set pict_type to AV_PICTURE_TYPE_NONE.
[hevc @ 0x55a354fa5f80] Application provided invalid, non monotonically increasing dts to muxer in stream 0: 3 >= 0
[hevc_qsv @ 0x55a354f29340] Error during encoding: unknown error (-21)
Video encoding failed
```

Is this a problem with an old version of the driver? According to apt, I am currently using:

```
Package: libmfx1
Version: 18.4.1-0ubuntu1

Package: intel-media-va-driver
Version: 18.4.1+dfsg1-2ubuntu1
```

Kernel version:

```
uname -a
Linux ... 5.0.0-29-generic #31-Ubuntu SMP Thu Sep 12 13:05:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

I opened an issue at the MediaSDK but apparently this is an user mode driver issue and got sent over here.

### LINKED ISSUE #930: [Issue] KO hardware decode/encode with Gemini lake family
## Desc: Hardware media decode/encode is KO with iHD driver on Gemini lake family
Unable to perform media decode/encode with iHD_drv_video.so, always have to force use of i965 driver. Impacts are degraded performance and capabilites: no HEVC 10bits for example or high CPU usage. Plus manual configuration is needed, like removal of iHD_drv_video.so or set up LIBVA_DRIVER_NAME to i965

## Current behavior
iHD_drv_video.so generate error message or hangs on Gemini lake processors

## Expected behavior
Working hardware decode as mention into VAAPI and Intel spec for GLK (especially HEVC 10bits HW encode)

## How to reproduce
1. run a Debian/Ubuntu/Alpine (docker or direct host)
2. install intel-media-driver package to get a working VAAPI
3. run a HW encode (plex, handbrake, ...), simple way is a handbrake test with H.265 Intel QSV (docker compose below)
4. CPU/GPU hangs, artifacts into generated files, error messages..
```
[16:42:39] hb_display_init: using VA driver 'iHD'
libva info: VA-API version 1.7.0
libva info: User environment variable requested driver 'iHD'
libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva info: va_openDriver() returns 0
[16:42:40] qsv_hevc_make_header: MFXVideoCORE_SyncOperation failed (-17)
[16:42:40] encqsvInit: qsv_hevc_make_header failed
[16:42:40] Failure to initialise thread 'Quick Sync Video encoder (Intel Media SDK)'
```

## Ecosystem
On my test case:
- Asrock j5005 
- running OMV5 (Debian 10)
- with docker and multiple images like LSIO Plex, Handbrake, ...

## Compose
```
version: '2.1'
services:
  handbrake:
    image: jlesage/handbrake
    container_name: handbrake
    environment:
      - USER_ID=1000
      - GROUP_ID=100
      - TZ=Europe/Paris
      #- LIBVA_DRIVER_NAME=i965
    ports:
      - 5800:5800
    volumes:
      - /srv/dev-disk-by-label-data/appdata/handbrake:/config:rw
      - /srv/dev-disk-by-label-media/media:/storage:ro
      - /srv/dev-disk-by-label-media/media/handbrake/watch:/watch:rw
      - /srv/dev-disk-by-label-media/media/handbrake/output:/output:rw
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
```

## Refs 
[plex forum - tons of users issues](https://forums.plex.tv/t/corrupted-video-output-stream-with-hardware-transcoding/500432/86)
[plex docker image](https://github.com/linuxserver/docker-plex/issues/228)
[maybe related to issue 733](https://github.com/intel/media-driver/issues/733)

### PR DESCRIPTION
**Pull request by Xiaogangli-intel**
Together with  #1005 can fix following 2 issues. Fixed #930, Fixed #733.

### CODE REVIEW

**Comment by JRDevo** [comment]
@XinfengZhang Please review?

@Xiaogangli-intel, can you please escalate this?

**Comment by Xiaogangli-intel** [comment]
@JRDevo 
Sure, will close this review tomorrow.

**Comment by JRDevo** [comment]
@Xiaogangli-intel, thank you kindly! :)

**Comment by XinfengZhang** [comment]
LGTM

**Pull request merged**
