### PR TITLE
Add additional CFL PCI IDs

### PR DESCRIPTION
**Pull request by cmpatel8588**
Signed-off-by: Chintan Patel <chintan.m.patel@intel.com>

### CODE REVIEW

**Comment by cmpatel8588** [comment]
Driver initialization fails due to missing PCI IDs on some boards:

	libva info: Trying to open /usr/lib64/va/drivers/iHD_drv_video.so
	libva info: Found init function __vaDriverInit_1_1
	libva error: /usr/lib64/va/drivers/iHD_drv_video.so init failed
	libva info: va_openDriver() returns 1
	vaInitialize failed with error code 1 (operation failed),exit

**Comment by wangyan42164** [comment]
@cmpatel8588 I think the setting of WHL devices based on  DID may need some changes after refer to the spec.
In your PR:
3ea0, 3ea1 - > gt2
3ea2, 3ea3, 3ea4 -> gt3

They should be:
3ea1 and 3ea4 -> gt1
3ea0 and 3ea3 -> gt2
3ea2 -> gt3

Could you change them and update the PR?
Thanks.

Yan Wang

**Comment by cmpatel8588** [comment]
Sure wangyan42164 ! I will work on that!

**Comment by cmpatel8588** [comment]
@wangyan42164 I noticed that you already submitted patch for this and its merged in master:

**5603c2766a58 [Decode] Add WHL DID for Chrome OS team.(CL#803694)**

Hence, I am assuming we don't need my patch anymore.

**Comment by wangyan42164** [comment]
@cmpatel8588 Because I cannot get your response and we have to finish the release as soon as possible, I had submitted one patch for WHL platform. You can update your PR for the other CFL devices. Thanks.

**Pull request closed without merging**
