### PR TITLE
Remove Gen10 support code

### PR DESCRIPTION
**Pull request by mattst88**
Gen10 graphics never shipped, and the support code was disabled by default in commit 99adba9ac ("Disable Gen10 driver code when -DGEN10=OFF") a few months ago.

````
 572 files changed, 2 insertions(+), 340589 deletions(-)
````

### CODE REVIEW

**Comment by mattst88** [comment]
Cc: @XinfengZhang

**Comment by mattst88** [comment]
Anything happening here?

**Comment by XinfengZhang** [comment]
@mattst88  what's the motivation about the change, it will not impact binary size, only impact the code base size.

**Comment by mattst88** [comment]
Right.

It seems like an obviously good thing for the codebase to remove 340 thousand lines of code that will never be used.

**Comment by versalinyaa** [comment]
I love drivers for gen10 gpus. The driver performance and quality is so unbelievable that it can't even be measured.

Despite my passion for git repos with a fat line count, though, this MR is obviously the right thing to do.

**Review by XinfengZhang — APPROVED** [review]

**Comment by XinfengZhang** [comment]
@mattst88 , could you help to rebase it?
suppose it still need some time to merge it. the change will be cherry-picked to some internal repo to verify whether there are other dependencies need to be removed., then merge it.

**Comment by mattst88** [comment]
Rebased.

Just ***once*** I would like to be able to have a contribution to this project accepted without needing to repeatedly ping the PR over multiple months.

**Comment by mattst88** [comment]
In case it wasn't apparent why removing Gen10 driver code was a good idea, take for example the (now two) cases of people wasting their time fixing Coverity issues in 100% dead code:

```
commit c1f57e463b924bfed35783b6530e2b86121894ae
Author: pengxin99 <pengxin.yuan@intel.com>
Date:   Tue Sep 26 13:36:57 2023 +0800

    [Decode] Fix some linux coverity issues
```

Do you need me to rebase this again?

**Comment by Sherry-Lin** [comment]
Yes, @mattst88 Would you help rebase again? There is long holiday in coming one week. Please expect the merge after holiday. Thanks.

**Comment by mattst88** [comment]
Rebased.

**Comment by mattst88** [comment]
```
commit c4442ddad7f8a83bcd2d9db24ebfcae5c64531ed
Author: luleilei1 <leileix.lu@intel.com>
Date:   Thu Sep 28 10:25:24 2023 +0800

    Revert "[Decode] Fix some linux coverity issues"
    
    This reverts commit intel-innersource/drivers.gpu.unified#c1f57e463

 media_driver/agnostic/gen10/hw/vdbox/mhw_vdbox_hcp_g10_X.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

Seriously? Stop this.

**Comment by hanlong1** [comment]
Hi @mattst88, can you rebase the change? new conflict happened during verification

**Pull request merged**
