### PR TITLE
Add Y212 and Y412 format

### LINKED ISSUE #998: vaQueryImageFormats does not return Y212 and Y412 format on TGL.
Y212 and Y412 formats should be returned if we want to decode 12 bits 422 and 444 streams in HEVC.
The Y216 and Y416 are returned, but we need to use 12 bits format, it is more precise. And I also notice that the P012 is available. 

Please also make sure Y212 and Y412 are in the list of vaQuerySurfaceAttributes's VASurfaceAttribPixelFormat, then we can make these formats as RT surface format of encoder/decoder context.

### PR DESCRIPTION
**Pull request by wangyan42164**
Fixes #998.

Signed-off-by: Yan Wang <yan.wang@linux.intel.com>

### CODE REVIEW

**Comment by wangyan42164** [comment]
This PR is dependent on https://github.com/intel/libva/pull/434.

**Comment by HeJunyan** [comment]
This patch is OK for me. Please merge it and the according 
https://github.com/intel/libva/pull/434 in libva.

I just test the decoder for 444 12 and 422 12. Is this patch enough for decoder and encoder, or the encoder still needs more patches?

**Comment by wangyan42164** [comment]
> This patch is OK for me. Please merge it and the according
> intel/libva#434 in libva.
> I just test the decoder for 444 12 and 422 12. Is this patch enough for decoder and encoder, or the encoder still needs more patches?

IMHO, it may be incomplete for encoding. Could you please try it? Thanks.

**Comment by FurongZhang** [comment]
This issue is more related to Codec.

**Comment by HeJunyan** [comment]
I test on my TGL, the result of applying this patch is:
1. We can successfully create Y412 and Y212 surface.
2. We failed to create Y412 or Y212 image.
3. Assign the Y212 and Y412 to decoder context of 444/42212bits profiles, the decoder process does not report error.
4. Because we fail to create the image of Y412 and Y212, I can not verify the result of the decoder(We can not call vaGetImage).
5. All the query of the context/config seems correct.
6. I can not verify the encoder, because we can not create Y412 and Y212 images and so, can not vaPutImage to a surface as encoder's input.

So, I think, we also need to support the Y412 or Y212 image, and its put/get functions here.

**Comment by wangyan42164** [comment]
> I test on my TGL, the result of applying this patch is:
> 
> 1. We can successfully create Y412 and Y212 surface.
> 2. We failed to create Y412 or Y212 image.
> 3. Assign the Y212 and Y412 to decoder context of 444/42212bits profiles, the decoder process does not report error.
> 4. Because we fail to create the image of Y412 and Y212, I can not verify the result of the decoder(We can not call vaGetImage).
> 5. All the query of the context/config seems correct.
> 6. I can not verify the encoder, because we can not create Y412 and Y212 images and so, can not vaPutImage to a surface as encoder's input.
> 
> So, I think, we also need to support the Y412 or Y212 image, and its put/get functions here.

Could you send your test command and clips for checking? We may need add Y412/Y212 support into vaGetImage/vaPutImgae. Thanks.

**Comment by HeJunyan** [comment]
Please  use https://gitlab.freedesktop.org/He_Junyan/gstreamer-vaapi    444_422_12bits_hevc_dec branch for gstreamer-vaapi.

command is
gst-launch-1.0 -f -v filesrc location=some12bits_stream ! h265parse ! vaapih265dec ! filesink location=output.yuv

in extract_allowed_surface_formats function, we will verify the Y212 and Y412 format image when pipeline is staring.

**Comment by wangyan42164** [comment]
@HeJunyan I have updated this PR. Could you please try it again? Thanks.

**Comment by wangyan-intel** [comment]
@XinfengZhang  We need update libva of CI build with intel/libva#434.

**Comment by wangyan42164** [comment]
@XinfengZhang I have added VA_VERSION_CHECK(1, 9, 0) for Y212/Y412 format. But we may stll need promote libva for including VA_FOURCC_Y212/Y412 definition which is under libva master branch. Thanks.

**Comment by HeJunyan** [comment]
The logic is correct now. My tools can not correctly display the 444-12 bits result. Can dumped file be displayed correctly on your tool?

**Comment by HeJunyan** [comment]
Updated the tool and verified, it's OK, thanks.

**Comment by wangyan-intel** [comment]
> Updated the tool and verified, it's OK, thanks.

Thanks for verification. After promote libva, we will push this PR to merge.

**Pull request merged**
