### PR TITLE
Fix transcoding performance issue on BDW.

### PR DESCRIPTION
**Pull request by TangZhiZhen**
Signed-off-by: ZhiZhen Tang <zhizhen.tang@intel.com>

### CODE REVIEW

**Comment by TangZhiZhen** [comment]
This patch is porting from PV5 HF1.

**Comment by TangZhiZhen** [comment]
yes, the perf drop only on BDW

**Comment by cchunbo** [comment]
> yes, the perf drop only on BDW
but the change will impact all platforms

**Comment by TangZhiZhen** [comment]
yes, we merged it on PV5 HF1 and run full test, it isn't impact on SKL platform.

**Comment by TangZhiZhen** [comment]
This issue was caused by CL722640. CL722640 can improve HEVC VME performance, but it is applied for all codecs. I changed this patch only for HEVC codec.

**Pull request merged**
