### PR TITLE
8K resolution size is only for HEVC not for AVC and VP9.

### LINKED ISSUE #540: [H264][DEC] Incorrected resolutions return
Found problem with h264 decode on BDW Ubuntu 18.04.. Function vaQueryConfigEntrypoints don't work correctly. This function returns 8192x8192 resolution for VAProfileH264High profile and VAEntrypointVLD entrypoint. But [it](https://github.com/intel/media-driver/blob/master/docs/media_features.md) says they the output resolution is 4K.
Commit 0e46d8574ca07d4580c20dadefd57a005213855a introduced regression. 
Based on the code this incorrect output may be found on other platforms.

### PR DESCRIPTION
**Pull request by wangyan42164**
Fixes #540.

Signed-off-by: Yan Wang <yan.wang@linux.intel.com>

### CODE REVIEW

**Comment by wangyan42164** [comment]
@XinfengZhang I refined it. Sorry for this. Could you please review it again?

**Comment by wangyan42164** [comment]
@XinfengZhang I changed it. Could you please review it again? Sorry.

**Comment by wangyan-intel** [comment]
@XinfengZhang Could you please review my refined PR? Thanks.

**Comment by XinfengZhang** [comment]
LGTM

**Pull request merged**
