### PR TITLE
Add support for ARGB10 composite format

### PR DESCRIPTION
**Pull request by Kishore409**
Signed-off-by: Kishore Kadiyala <kishore.kadiyala@intel.com>

### CODE REVIEW

**Comment by FurongZhang** [comment]
It failed. Can you please check?

**Comment by Kishore409** [comment]
> It failed. Can you please check?

travis-CI log indicates there is a compilation failure , not related to my change

<snip>
media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/gen11_icllp/vp/hal/vphal_renderer_g11_icllp.cpp.o
/opt/src/media-driver/media_driver/agnostic/gen11_icllp/media_interfaces/media_interfaces_g11_ehl.cpp:31:10: fatal error: igcodeckrn_g11.h: No such file or directory
 #include "igcodeckrn_g11.h"
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/build.make:7814: recipe for target 'media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/gen11_icllp/media_interfaces/media_interfaces_g11_ehl.cpp.o' failed
make[2]: *** [media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/agnostic/gen11_icllp/media_interfaces/media_interfaces_g11_ehl.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/all] Error 2
CMakeFiles/Makefile2:239: recipe for target 'media_driver/CMakeFiles/iHD_drv_video_OBJ.dir/all' failed
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by XinfengZhang** [comment]
@Kishore409  the pull request incorrectly include other commit

**Comment by Kishore409** [comment]
> @Kishore409  the pull request incorrectly include other commit

@XinfengZhang Not sure how all that got added
This is the PR : https://github.com/intel/media-driver/pull/793
It doesn't have any patches

**Comment by XinfengZhang** [comment]
duplicate with #793

**Pull request closed without merging**
