### PR TITLE
[Encode] Update HEVC 422 in README

### PR DESCRIPTION
**Pull request by OttoYang**
Enable HEVC 8/10 bit 422 capability in readme.md

### CODE REVIEW

**Comment by Sherry-Lin** [comment]
Thanks Otto. Could you update feature page together? https://github.com/intel/media-driver/blob/master/docs/media_features.md#supported-encoding-input-format-and-max-resolution

**Comment by bai-isaac** [comment]
could you please update MTL HEVC 422 too?

**Review by bai-isaac — APPROVED** [review]
lgtm

**Comment by OttoYang** [comment]
> could you please update MTL HEVC 422 too?

We only enable HEVC 422 on ATSM now.

**Review by Sherry-Lin — APPROVED** [review]
looks good

**Pull request merged**
